EMBEDDING_MODEL = "gemini-embedding-2"
GENERATION_MODEL = "gemini-2.5-flash"
GROQ_FALLBACK_MODEL = "llama-3.3-70b-versatile"
MAX_OUTPUT_TOKENS = 500

CHUNK_SIZE = 500
CHUNK_OVERLAP = 50
MAX_PDF_PAGES = 6

SIMILARITY_HIGH = 0.75
SIMILARITY_LOW = 0.55
MATCH_CANDIDATES = 20

ACCESS_TOKEN_COOKIE = "access_token"
REFRESH_TOKEN_COOKIE = "refresh_token"
